# Generated by Django 3.0.3 on 2020-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0002_auto_20201102_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='image',
            field=models.ImageField(blank=True, upload_to='criminal/images'),
        ),
    ]
