# Generated by Django 3.0.3 on 2020-11-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('home_address', models.CharField(max_length=250)),
                ('contactno', models.CharField(max_length=10)),
            ],
        ),
    ]
